apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: service-tracker-managed
spec:
  components:
    - componentName: tracker-managed-postgres-db
      parameterValues:
        - name: dbconn
          value: trackerdbconn
    - componentName: data-api
      parameterValues:
        - name: dbsecret
          value: trackerdbconn
        - name: dbname
          value: postgres 
        - name: dbport
          value: "5432"
        - name: dbdriver
          value: "postgres"
        - name: dboptions
          value: ""
    - componentName: flights-api
      parameterValues:
        - name: dataUri
          value: "http://data-api.default.svc.cluster.local:3009/"
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: ManualScalerTrait
            metadata:
              name: flights-api
            spec:
              replicaCount: 2
    - componentName: quakes-api
      parameterValues:
        - name: dataUri
          value: "http://data-api.default.svc.cluster.local:3009/"  
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: ManualScalerTrait
            metadata:
              name: quakes-api
            spec:
              replicaCount: 2 
    - componentName: weather-api
      parameterValues:
        - name: dataUri
          value: "http://data-api.default.svc.cluster.local:3009/"
      traits:
        - trait:
            apiVersion: core.oam.dev/v1alpha2
            kind: ManualScalerTrait
            metadata:
              name: weather-api
            spec:
              replicaCount: 2       
    - componentName: service-tracker-ui
      parameterValues:
        - name: flightsUri
          value: "http://flights-api.default.svc.cluster.local:3003/"
        - name: weatherUri
          value: "http://weather-api.default.svc.cluster.local:3015/"
        - name: quakesUri
          value: "http://quakes-api.default.svc.cluster.local:3012/"